version: "3.0"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt
    command: "python manage.py runserver 0.0.0.0:8000"
